version: '3'
services:
  database:
    image: vuejs/pencatatan:1.0.0
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  vuejs:
    image: vuejs/pencatatan:latest
    ports:
      - 1500:1500
    volumes:
      - '../Belajar Astro/violet-venus/public/directus_uploads:/directus/uploads'
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'huda@gmail.com'
      ADMIN_PASSWORD: 'ayamgoreng'

      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
